name: Deploy to OVH (FTPS)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: SFTP Deploy (lftp mirror)
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          user: ${{ secrets.SFTP_USERNAME }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          localDir: "dist"
          remoteDir: "/www"
          reverse: "true"          # push local -> remote
          onlyNewer: "false"       # on envoie tout (pour être sûr)
          restoreMTime: "true"     # conserve la date modif
          parallel: "2"
          # 'delete' n'est pas un input supporté → on le passe dans options
          options: "--delete --verbose=3"
          # Petits réglages lftp utiles (auto-accept host key, timeouts…)
          settings: |
            set sftp:auto-confirm yes
            set net:max-retries 2
            set net:timeout 20