name: Deploy to OVH (FTPS)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: SFTP Deploy (lftp mirror)
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          user: ${{ secrets.SFTP_USERNAME }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          # Chemins
          localDir: "dist"
          remoteDir: "/www"
          # Miroir local -> distant
          reverse: "true"
          delete: "true"          # supprime côté serveur ce qui n'existe plus localement
          onlyNewer: "false"
          options: "--verbose=3 --parallel=2"
