name: Deploy to OVH (FTPS)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci
        
      - name: Create .env.production for Vite
        run: |
          cat > .env.production <<'EOF'
          VITE_MAKE_WEBHOOK_URL=${{ secrets.VITE_MAKE_WEBHOOK_URL }}
          VITE_CONTACT_WEBHOOK_URL=${{ secrets.VITE_CONTACT_WEBHOOK_URL }}
          EOF

      - name: Build
        run: npm run build

      - name: SFTP Deploy (lftp mirror)
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          user: ${{ secrets.SFTP_USERNAME }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          port: 22

          # Chemins (IMPORTANT : pas de / devant www)
          localDir: "dist"
          remoteDir: "www"

          # push local -> remote
          reverse: "true"

          # On pousse tous les fichiers (tu pourras remettre true plus tard si tu veux ne pousser que les plus récents)
          onlyNewer: "false"

          # Conserve les dates mtime / 2 transferts en parallèle
          restoreMTime: "true"
          parallel: "2"

          # Supprime côté serveur ce qui n'existe plus localement
          # (tu peux enlever --delete pour le 1er run si tu veux être rassuré)
          options: "--delete --verbose=3"

          # Réglages lftp (simples & safe)
          settings: |
            set sftp:auto-confirm yes
            set net:max-retries 2
            set net:timeout 20
